version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-dev --optimize-autoloader

  build:
    commands:
      - echo "Build step here (e.g., php artisan config:cache)"
      - php artisan config:cache

  post_build:
    commands:
      - echo "Post build step finished"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '.git/**'
    - 'node_modules/**'
